"""empty message

Revision ID: 31abc6719d70
Revises: f599f81604b2
Create Date: 2021-07-08 00:35:07.002000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31abc6719d70'
down_revision = 'f599f81604b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_user_account_id_fkey', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'user_account', ['user_account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('result__track_result_id_fkey', 'result__track', type_='foreignkey')
    op.create_foreign_key(None, 'result__track', 'result', ['result_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result__track', type_='foreignkey')
    op.create_foreign_key('result__track_result_id_fkey', 'result__track', 'result', ['result_id'], ['id'])
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.create_foreign_key('result_user_account_id_fkey', 'result', 'user_account', ['user_account_id'], ['id'])
    # ### end Alembic commands ###
